chore: Support sub domain (#43)
Signed-off-by: Ce Gao <cegao@tensorchord.ai>

diff --git a/ingress-operator/Makefile b/ingress-operator/Makefile
--- a/ingress-operator/Makefile
+++ b/ingress-operator/Makefile
@@ -1,110 +1,186 @@
-TAG?=dev
-SERVER?=docker.io
-OWNER?=tensorchord
-IMAGE := ingress-operator
+# Copyright 2022 TensorChord Inc.
+#
+# The old school Makefile, following are required targets. The Makefile is written
+# to allow building multiple binaries. You are free to add more targets or change
+# existing implementations, as long as the semantics are preserved.
+#
+#   make              - default to 'build' target
+#   make lint         - code analysis
+#   make test         - run unit test (or plus integration test)
+#   make build        - alias to build-local target
+#   make build-local  - build local binary targets
+#   make build-linux  - build linux binary targets
+#   make container    - build containers
+#   $ docker login registry -u username -p xxxxx
+#   make push         - push containers
+#   make clean        - clean up targets
+#
+# Not included but recommended targets:
+#   make e2e-test
+#
+# The makefile is also responsible to populate project version information.
+#
+
+#
+# Tweak the variables based on your project.
+#
+
 # This repo's root import path (under GOPATH).
 ROOT := github.com/tensorchord/openmodelz/ingress-operator
 
 # Target binaries. You can build multiple binaries for a single project.
 TARGETS := ingress-operator
+
+# Container image prefix and suffix added to targets.
+# The final built images are:
+#   $[REGISTRY]/$[IMAGE_PREFIX]$[TARGET]$[IMAGE_SUFFIX]:$[VERSION]
+# $[REGISTRY] is an item from $[REGISTRIES], $[TARGET] is an item from $[TARGETS].
+IMAGE_PREFIX ?= $(strip )
+IMAGE_SUFFIX ?= $(strip )
+
+# Container registries.
+REGISTRY ?= ghcr.io/tensorchord
+
+# Container registry for base images.
+BASE_REGISTRY ?= docker.io
+BASE_REGISTRY_USER ?= modelzai
+
 # Disable CGO by default.
 CGO_ENABLED ?= 0
+
+#
+# These variables should not need tweaking.
+#
+
+# It's necessary to set this because some environments don't link sh -> bash.
+export SHELL := bash
+
+# It's necessary to set the errexit flags for the bash shell.
+export SHELLOPTS := errexit
+
+PACKAGE_NAME := github.com/tensorchord/openmodelz/ingress-operator
+GOLANG_CROSS_VERSION  ?= v1.17.6
+
 # Project main package location (can be multiple ones).
-CMD_DIR := ./
-OUTPUT_DIR := ./
+CMD_DIR := ./cmd
 
-.GIT_COMMIT=$(shell git rev-parse HEAD)
-.GIT_VERSION=$(shell git describe --tags 2>/dev/null || echo "$(.GIT_COMMIT)")
-.GIT_UNTRACKEDCHANGES := $(shell git status --porcelain --untracked-files=no)
-ifneq ($(.GIT_UNTRACKEDCHANGES),)
-	.GIT_COMMIT := $(.GIT_COMMIT)-dirty
-endif
+# Project output directory.
+OUTPUT_DIR := ./bin
+DEBUG_DIR := ./debug-bin
 
-# docker manifest command will work with Docker CLI 18.03 or newer
-# but for now it's still experimental feature so we need to enable that
-export DOCKER_CLI_EXPERIMENTAL=enabled
+# Build directory.
+BUILD_DIR := ./build
 
-TOOLS_DIR := .tools
+# Current version of the project.
+VERSION ?= $(shell git describe --match 'v[0-9]*' --always --tags --abbrev=0)
+BUILD_DATE=$(shell date -u +'%Y-%m-%dT%H:%M:%SZ')
+GIT_COMMIT=$(shell git rev-parse HEAD)
+GIT_TAG=$(shell if [ -z "`git status --porcelain`" ]; then git describe --exact-match --tags HEAD 2>/dev/null; fi)
+GIT_TREE_STATE=$(shell if [ -z "`git status --porcelain`" ]; then echo "clean" ; else echo "dirty"; fi)
+GITSHA ?= $(shell git rev-parse --short HEAD)
 
-GOPATH := $(shell go env GOPATH)
-CODEGEN_VERSION := $(shell hack/print-codegen-version.sh)
-CODEGEN_PKG := $(GOPATH)/pkg/mod/k8s.io/code-generator@${CODEGEN_VERSION}
+# Track code version with Docker Label.
+DOCKER_LABELS ?= git-describe="$(shell date -u +v%Y%m%d)-$(shell git describe --tags --always --dirty)"
 
+# Golang standard bin directory.
+GOPATH ?= $(shell go env GOPATH)
+GOROOT ?= $(shell go env GOROOT)
+BIN_DIR := $(GOPATH)/bin
+GOLANGCI_LINT := $(BIN_DIR)/golangci-lint
 
+# check if we need embed the dashboard
+DASHBOARD_BUILD ?= debug
 
-ARCH?=linux/amd64
-MULTIARCH?=linux/amd64,linux/arm/v7,linux/arm64
+# Default golang flags used in build and test
+# -mod=vendor: force go to use the vendor files instead of using the `$GOPATH/pkg/mod`
+# -p: the number of programs that can be run in parallel
+# -count: run each test and benchmark 1 times. Set this flag to disable test cache
+export GOFLAGS ?= -count=1
 
-$(TOOLS_DIR)/code-generator.mod: go.mod
-	@echo "syncing code-generator tooling version"
-	@cd $(TOOLS_DIR) && go mod edit -require "k8s.io/code-generator@${CODEGEN_VERSION}"
+#
+# Define all targets. At least the following commands are required:
+#
 
-${CODEGEN_PKG}: $(TOOLS_DIR)/code-generator.mod
-	@echo "(re)installing k8s.io/code-generator-${CODEGEN_VERSION}"
-	@cd $(TOOLS_DIR) && go mod download -modfile=code-generator.mod
+# All targets.
+.PHONY: help lint test build container push addlicense debug debug-local build-local generate clean test-local addlicense-install release build-image
 
-.PHONY: build
-build: build-local
-	@echo "building  $(SERVER)/$(OWNER)/$(IMAGE):$(TAG)-$(.GIT_COMMIT)"
-	@docker build \
-	--build-arg VERSION=$(.GIT_VERSION) \
-	--build-arg GIT_COMMIT=$(.GIT_COMMIT) \
-	-t  $(SERVER)/$(OWNER)/$(IMAGE):$(TAG)-$(.GIT_COMMIT) .
-	@rm -rf ingress-operator
-	@docker push $(SERVER)/$(OWNER)/$(IMAGE):$(TAG)-$(.GIT_COMMIT) 
+.DEFAULT_GOAL:=build
 
-.PHONY: build-local
+build: build-local  ## Build the release version of envd
+
+help:  ## Display this help
+	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n"} /^[a-zA-Z0-9_-]+:.*?##/ { printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)
+
+debug: debug-local  ## Build the debug version of envd
+
+# more info about `GOGC` env: https://github.com/golangci/golangci-lint#memory-usage-of-golangci-lint
+lint: $(GOLANGCI_LINT)  ## Lint GO code
+	@$(GOLANGCI_LINT) run
+
+$(GOLANGCI_LINT):
+	curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $$(go env GOPATH)/bin
+
+mockgen-install:
+	go install github.com/golang/mock/mockgen@v1.6.0
+
+addlicense-install:
+	go install github.com/google/addlicense@latest
+
 build-local:
 	@for target in $(TARGETS); do                                                      \
-		CGO_ENABLED=$(CGO_ENABLED) GOOS=$(GOOS) GOARCH=$(GOARCH) go build -tags $(DASHBOARD_BUILD)  -trimpath -v -o $(OUTPUT_DIR)/$${target}     \
-		-ldflags "-s -w -X $(ROOT)/pkg/version.version=$(VERSION) -X $(ROOT)/pkg/version.buildDate=$(BUILD_DATE) -X $(ROOT)/pkg/version.gitCommit=$(GIT_COMMIT) -X $(ROOT)/pkg/version.gitTreeState=$(GIT_TREE_STATE)"                     \
-		$(CMD_DIR)/;                                                         \
+	  CGO_ENABLED=$(CGO_ENABLED) GOOS=$(GOOS) GOARCH=$(GOARCH) go build -tags $(DASHBOARD_BUILD)  -trimpath -v -o $(OUTPUT_DIR)/$${target}     \
+	    -ldflags "-s -w -X $(ROOT)/pkg/version.version=$(VERSION) -X $(ROOT)/pkg/version.buildDate=$(BUILD_DATE) -X $(ROOT)/pkg/version.gitCommit=$(GIT_COMMIT) -X $(ROOT)/pkg/version.gitTreeState=$(GIT_TREE_STATE)"                     \
+	    $(CMD_DIR)/$${target};                                                         \
 	done
 
-.PHONY: build-buildx
-build-buildx:
-	@echo  $(SERVER)/$(OWNER)/$(IMAGE):$(TAG) && \
-	docker buildx create --use --name=multiarch --node=multiarch && \
-	docker buildx build \
-		--push \
-		--platform $(ARCH) \
-		--build-arg VERSION=$(.GIT_VERSION) \
-		--build-arg GIT_COMMIT=$(.GIT_COMMIT) \
-		--tag  $(SERVER)/$(OWNER)/$(IMAGE):$(TAG) \
-		.
+# It is used by vscode to attach into the process.
+debug-local:
+	@for target in $(TARGETS); do                                                      \
+	  CGO_ENABLED=$(CGO_ENABLED) go build -tags $(DASHBOARD_BUILD) -trimpath                                    \
+	  	-v -o $(DEBUG_DIR)/$${target}                                                  \
+	  	-gcflags='all=-N -l'                                                           \
+	    $(CMD_DIR)/$${target};                                                         \
+	done
 
-.PHONY: build-buildx-all
-build-buildx-all:
-	@echo  "build $(SERVER)/$(OWNER)/$(IMAGE):$(TAG) for $(MULTIARCH)"
-	@docker buildx create --use --name=multiarch --node=multiarch && \
-	docker buildx build \
-		--platform $(MULTIARCH) \
-		--output "type=image,push=false" \
-		--build-arg VERSION=$(.GIT_VERSION) \
-		--build-arg GIT_COMMIT=$(.GIT_COMMIT) \
-		--tag $(SERVER)/$(OWNER)/$(IMAGE):$(TAG) \
-		.
+addlicense: addlicense-install  ## Add license to GO code files
+	addlicense -l mpl -c "TensorChord Inc." $$(find . -type f -name '*.go' | grep -v pkg/docs/docs.go)
 
-.PHONY: publish-buildx-all
-publish-buildx-all:
-	@echo  "build and publish $(SERVER)/$(OWNER)/$(IMAGE):$(TAG) for $(MULTIARCH)"
-	@docker buildx create --use --name=multiarch --node=multiarch && \
-	docker buildx build \
-		--platform $(MULTIARCH) \
-		--push=true \
-		--build-arg VERSION=$(.GIT_VERSION) \
-		--build-arg GIT_COMMIT=$(.GIT_COMMIT) \
-		--tag $(SERVER)/$(OWNER)/$(IMAGE):$(TAG) \
-		.
+test-local:
+	@go test -tags=$(DASHBOARD_BUILD) -v -race -coverprofile=coverage.out ./...
 
-.PHONY: test
-test:
-	go test -v ./...
+test:  ## Run the tests
+	@go test -tags=$(DASHBOARD_BUILD) -race -coverpkg=./pkg/... -coverprofile=coverage.out ./...
+	@go tool cover -func coverage.out | tail -n 1 | awk '{ print "Total coverage: " $$3 }'
 
-.PHONY: verify-codegen
-verify-codegen: ${CODEGEN_PKG}
-	./hack/verify-codegen.sh
+clean:  ## Clean the outputs and artifacts
+	@-rm -vrf ${OUTPUT_DIR}
+	@-rm -vrf ${DEBUG_DIR}
+	@-rm -vrf build dist .eggs *.egg-info
 
-.PHONY: update-codegen
-update-codegen: ${CODEGEN_PKG}
-	./hack/update-codegen.sh
+fmt: swag-install ## Run go fmt against code.
+	go fmt ./...
+	swag fmt
+
+vet: ## Run go vet against code.
+	go vet ./...
+
+build-image: build-local
+	docker build -t ${BASE_REGISTRY}/${BASE_REGISTRY_USER}/modelzetes:dev -f Dockerfile ./bin
+	docker push ${BASE_REGISTRY}/${BASE_REGISTRY_USER}/modelzetes:dev
+
+release:
+	@if [ ! -f ".release-env" ]; then \
+		echo "\033[91m.release-env is required for release\033[0m";\
+		exit 1;\
+	fi
+	docker run \
+		--rm \
+		--privileged \
+		-e CGO_ENABLED=1 \
+		--env-file .release-env \
+		-v /var/run/docker.sock:/var/run/docker.sock \
+		-v `pwd`:/go/src/$(PACKAGE_NAME) \
+		-v `pwd`/sysroot:/sysroot \
+		-w /go/src/$(PACKAGE_NAME) \
+		goreleaser/goreleaser-cross:${GOLANG_CROSS_VERSION} \
+		release --rm-dist
